name: .NET

on:
  push:
    branches: [ '**' ]
    paths-ignore: [ '**/README.md' ]
  pull_request:
    branches: [ '**' ]
    paths-ignore: [ '**/README.md' ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        dotnet-version: [ '5.0.x', '6.0.x' ]

    steps:
    - uses: actions/checkout@v2

    - name: Setup .NET ${{ matrix.dotnet-version }}
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: ${{ matrix.dotnet-version }}

    - name: Restore dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build --no-restore

    - name: Test
      run: dotnet test --no-build --verbosity normal
